"""Generated C2PA soft-binding registry; do not edit by hand.

Source: https://raw.githubusercontent.com/c2pa-org/softbinding-algorithm-list/main/softbinding-algorithm-list.json
Revision: c0218cd628c9163ad62a08c3deff5a10fa0e0d0b
Source license: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
Changes: validated, ordered, and reduced to fields used at runtime; descriptions
are shortened to their first sentence for display.
"""

from __future__ import annotations

C2PA_SOFT_BINDING_SOURCE_URL = (
    "https://raw.githubusercontent.com/c2pa-org/softbinding-algorithm-list/main/softbinding-algorithm-list.json"
)
C2PA_SOFT_BINDING_SOURCE_REVISION = "c0218cd628c9163ad62a08c3deff5a10fa0e0d0b"
C2PA_SOFT_BINDING_SOURCE_LICENSE = "CC BY 4.0"

C2PA_SOFT_BINDING_ROWS: tuple[
    tuple[int, str, str, tuple[str, ...], tuple[str, ...], str, str, tuple[str, ...], bool], ...
] = (
    (
        1,
        "com.digimarc.validate.1",
        "watermark",
        ("audio", "video", "text", "image"),
        (),
        "Digimarc Validate Digital Watermarking algorithm",
        "2024-05-17T17:00:00.000Z",
        (),
        False,
    ),
    (
        2,
        "org.atsc.a336",
        "watermark",
        ("audio", "video", "image"),
        (),
        "ATSC watermarking (A/334, A/335, A/336)",
        "2024-05-17T15:43:00.000Z",
        (),
        False,
    ),
    (
        3,
        "io.iscc.v0",
        "fingerprint",
        ("text", "image", "audio", "video", "application"),
        (),
        "ISO 24138 - International Standard Content Code (ISCC) V0 algorithm",
        "2024-05-17T16:00:00Z",
        (),
        False,
    ),
    (
        4,
        "com.adobe.trustmark.Q",
        "watermark",
        ("image",),
        (),
        "Adobe Trustmark variant Q",
        "2024-05-17T17:00:00.000Z",
        (),
        False,
    ),
    (
        5,
        "com.adobe.trustmark.C",
        "watermark",
        ("image",),
        (),
        "Adobe Trustmark variant C",
        "2024-05-17T17:00:00.000Z",
        (),
        False,
    ),
    (
        6,
        "com.adobe.icn.dense",
        "fingerprint",
        ("image",),
        (),
        "Adobe Image Comparator Network Dense Fingerprint",
        "2024-05-17T17:00:00.000Z",
        (),
        False,
    ),
    (
        7,
        "ai.steg.api",
        "watermark",
        ("image", "video", "application"),
        (),
        "Steg.AI invisible watermarking",
        "2024-05-20T10:50:00.000Z",
        (),
        False,
    ),
    (
        8,
        "ai.trufo.pawprint.watermark",
        "watermark",
        ("image", "audio", "video"),
        (),
        "PawPrint neural watermarking for images, audio, and video",
        "2024-08-14T15:00:00.000Z",
        ("https://c2pa.trufo.ai/v1",),
        False,
    ),
    (
        9,
        "ai.trufo.pawprint.fingerprint",
        "fingerprint",
        ("image", "audio", "video"),
        (),
        "PawPrint neural fingerprinting for images, audio, and video",
        "2024-08-14T15:00:00.000Z",
        ("https://c2pa.trufo.ai/v1",),
        False,
    ),
    (
        10,
        "app.overlai.watermark.1",
        "watermark",
        ("image",),
        (),
        "Overlai Watermark version 1",
        "2024-08-14T16:00:00.000Z",
        (),
        False,
    ),
    (
        11,
        "tv.kinetiq.watercast.48.1",
        "watermark",
        ("video",),
        (),
        "Teletrax Watermarking algorithm",
        "2024-10-16T17:00:00.000Z",
        (),
        False,
    ),
    (
        12,
        "castLabs.watermark.1",
        "watermark",
        ("video", "image", "audio"),
        (),
        "castLabs Single Frame Forensic Watermarking",
        "2024-11-13T12:00:00.000Z",
        (),
        False,
    ),
    (
        13,
        "com.adobe.trustmark.P",
        "watermark",
        ("image",),
        (),
        "Adobe Trustmark variant P",
        "2025-02-05T17:00:00.000Z",
        (),
        False,
    ),
    (
        14,
        "com.imatag.lamark.v1",
        "watermark",
        ("image",),
        (),
        "Imatag invisible watermarking for images",
        "2025-02-26T15:00:00.000Z",
        (),
        False,
    ),
    (
        15,
        "com.nagra.nexguard.watermark.1",
        "watermark",
        ("video", "audio", "image"),
        (),
        "NAGRA NexGuard Watermarking with Single Frame Detection Capability",
        "2025-02-26T13:53:25.000Z",
        (),
        False,
    ),
    (
        16,
        "com.mentaport.watermark.1",
        "watermark",
        ("video", "audio", "image"),
        (),
        "Mentaport Watermarking Engine",
        "2025-03-12T13:00:00.000Z",
        (),
        False,
    ),
    (
        17,
        "com.digicaps.fingerprint.1",
        "fingerprint",
        ("image",),
        (),
        "DigiCAP Fingerprint Engine",
        "2025-06-16T17:00:00.000Z",
        (),
        False,
    ),
    (
        18,
        "com.sonicorigin.watermark.1",
        "watermark",
        ("audio", "video"),
        (),
        "SonicOrigin Watermarking Engine",
        "2025-08-13T18:25:00.000Z",
        (),
        False,
    ),
    (
        19,
        "com.microsoft.invismark.1",
        "watermark",
        ("image", "video"),
        (),
        "Microsoft Responsible AI InvisMark",
        "2025-10-12T18:25:00.000Z",
        (),
        False,
    ),
    (
        20,
        "com.microsoft.wavmark.1",
        "watermark",
        ("audio", "video"),
        (),
        "Microsoft Responsible AI WavMark",
        "2025-10-12T15:00:00.000Z",
        (),
        False,
    ),
    (
        21,
        "ai.contentlens.image.basewmk",
        "watermark",
        ("image",),
        (),
        "ContentLens Image Watermarking (Base)",
        "2025-11-26T14:30:00.000Z",
        (),
        False,
    ),
    (
        22,
        "ai.contentlens.image.ensemblewmk",
        "watermark",
        ("image",),
        (),
        "ContentLens Image Watermarking (Ensemble)",
        "2025-11-26T14:30:00.000Z",
        (),
        False,
    ),
    (
        23,
        "ai.contentlens.image.customwmk",
        "watermark",
        ("image",),
        (),
        "ContentLens Image Watermarking (Custom)",
        "2025-11-26T14:30:00.000Z",
        (),
        False,
    ),
    (
        24,
        "ai.contentlens.audio.mono",
        "watermark",
        ("audio",),
        (),
        "ContentLens Audio Watermarking (Mono)",
        "2025-11-26T14:30:00.000Z",
        (),
        False,
    ),
    (
        25,
        "ai.contentlens.audio.stereo",
        "watermark",
        ("audio",),
        (),
        "ContentLens Audio Watermarking (Stereo)",
        "2025-11-26T14:30:00.000Z",
        (),
        False,
    ),
    (
        26,
        "es.lumatrace",
        "watermark",
        ("image",),
        (),
        "Java-native Adaptive Spatial Watermarking using Blue-channel injection",
        "2026-01-26T17:30:00.000Z",
        (),
        False,
    ),
    (
        27,
        "com.markany.watermark.1",
        "watermark",
        ("image", "video", "audio"),
        (),
        "MarkAny invisible watermarking with robustness against cropping, resizing, and compression",
        "2026-02-25T00:00:00.000Z",
        (),
        False,
    ),
    (
        28,
        "com.verimatrix.watermark.1",
        "watermark",
        ("video",),
        (),
        (
            "Verimatrix watermarking algorithm: provides an essence-based forensic watermarking "
            "mechanism that may be used as a C2PA soft-binding technology"
        ),
        "2026-02-26T14:16:00.000Z",
        (),
        False,
    ),
    (
        29,
        "com.writerslogic.zwc-watermark.1",
        "watermark",
        (),
        ("text/plain", "text/markdown", "text/html"),
        "WritersLogic CPOP zero-width character (ZWC) watermark for text content",
        "2026-03-18T20:00:00.000Z",
        (),
        False,
    ),
    (
        30,
        "com.aiwatermark.videoseal.1",
        "watermark",
        ("video",),
        ("video/mp4", "video/webm"),
        (
            "Neural video watermarking using Meta FAIR's VideoSeal model, providing perceptually "
            "invisible soft-binding watermarks in video content"
        ),
        "2026-03-08T00:00:00.000Z",
        ("https://aiwatermark.com/api/v1",),
        False,
    ),
    (
        31,
        "com.aiwatermark.pixelseal.1",
        "watermark",
        ("image",),
        ("image/png", "image/jpeg", "image/webp"),
        (
            "Neural image watermarking using Meta FAIR's PixelSeal model, providing perceptually "
            "invisible soft-binding watermarks in image content"
        ),
        "2026-03-08T00:00:00.000Z",
        ("https://aiwatermark.com/api/v1",),
        False,
    ),
    (
        32,
        "com.aiwatermark.audioseal.1",
        "watermark",
        ("audio",),
        ("audio/mpeg", "audio/wav", "audio/flac", "audio/mp4"),
        (
            "Neural audio watermarking using Meta FAIR's AudioSeal model, providing imperceptible "
            "soft-binding watermarks in audio content"
        ),
        "2026-03-08T00:00:00.000Z",
        ("https://aiwatermark.com/api/v1",),
        False,
    ),
    (
        33,
        "eu.sasha.softbinding.v1",
        "watermark",
        ("image",),
        ("image/jpeg", "image/png"),
        (
            "Invisible watermarking technology for image and video assets, enabling C2PA manifest "
            "recovery and content provenance verification after metadata stripping or transcoding"
        ),
        "2026-04-16T00:00:00.000Z",
        (),
        False,
    ),
    (
        34,
        "ai.verda.watermark.image.1",
        "watermark",
        ("image",),
        ("image/png", "image/jpeg", "image/avif"),
        "VerdaAI invisible image watermarking",
        "2026-04-16T00:00:00.000Z",
        (),
        False,
    ),
    (
        35,
        "ai.verda.watermark.video.1",
        "watermark",
        ("video",),
        ("video/mp4", "video/webm", "video/quicktime"),
        "VerdaAI invisible video watermarking",
        "2026-04-16T00:00:00.000Z",
        (),
        False,
    ),
    (
        36,
        "ai.verda.watermark.audio.1",
        "watermark",
        ("audio",),
        ("audio/mpeg", "audio/wav", "audio/aac", "audio/ogg", "audio/flac"),
        "VerdaAI invisible audio watermarking",
        "2026-04-16T00:00:00.000Z",
        (),
        False,
    ),
    (
        37,
        "com.evixar.eaw.1",
        "watermark",
        ("audio", "video"),
        (),
        "EAW (Evixar Audio Watermark) is an audible-range audio watermarking algorithm developed by Evixar Inc",
        "2026-04-24T00:00:00.000Z",
        (),
        False,
    ),
    (
        38,
        "com.evixar.efp.type3.1",
        "fingerprint",
        ("audio", "video"),
        (),
        "EFP Type 3 (Evixar Finger Print Type 3) is an audio fingerprinting algorithm developed by Evixar Inc",
        "2026-04-24T00:00:00.000Z",
        (),
        False,
    ),
    (
        39,
        "com.cognitive-proof.vsrmark.1",
        "watermark",
        ("text",),
        (),
        (
            "VSRMark hides a structured byte payload inside visible Unicode text by appending "
            "invisible Variation Selectors after visible characters"
        ),
        "2026-06-04T00:00:00.000Z",
        (),
        False,
    ),
    (
        40,
        "me.deepmark.audio.vigil.128",
        "watermark",
        ("audio",),
        (),
        "Vigil is a 128-bit-per-second neural audio watermarking algorithm developed by DeepMark Inc",
        "2026-06-05T00:00:00Z",
        ("https://resolution-api.deepmark.me",),
        False,
    ),
    (
        41,
        "com.writerslogic.text-fingerprint.1",
        "fingerprint",
        (),
        ("text/plain", "text/markdown", "text/html"),
        "WritersLogic CPoE robust text fingerprint",
        "2026-06-22T00:00:00.000Z",
        (),
        False,
    ),
    (
        42,
        "com.writerslogic.zwc-watermark.2",
        "watermark",
        (),
        ("text/plain", "text/markdown", "text/html"),
        "Revision of com.writerslogic.zwc-watermark.1",
        "2026-07-07T00:00:00.000Z",
        (),
        False,
    ),
    (
        43,
        "com.writerslogic.text-structure.1",
        "fingerprint",
        (),
        ("text/plain", "text/markdown", "text/html"),
        "WritersLogic CPoE structural text fingerprint",
        "2026-07-07T00:00:00.000Z",
        (),
        False,
    ),
    (
        44,
        "com.writerslogic.text-minhash.1",
        "fingerprint",
        (),
        ("text/plain", "text/markdown", "text/html"),
        "WritersLogic CPoE lexical MinHash text fingerprint for excerpt and quotation matching",
        "2026-07-07T00:00:00.000Z",
        (),
        False,
    ),
    (
        45,
        "io.blockfact.audio.watermark.32",
        "watermark",
        ("audio", "image", "video"),
        (),
        "BlockFact invisible watermarking for audio, image, and video provenance",
        "2026-07-10T16:00:00.000Z",
        ("https://api.blockfact.io/api/soft-binding/v1",),
        False,
    ),
    (
        46,
        "com.doverunner.watermark.1",
        "watermark",
        ("video",),
        (),
        (
            "DoveRunner's forensic watermarking solution delivers invisible, tamper-resilient "
            "traceability into video content — from enterprise distribution pipelines to "
            "end-consumer playback"
        ),
        "2026-07-27T14:00:00.000Z",
        (),
        False,
    ),
    (
        47,
        "com.writerslogic.text-watermark-semantic.1",
        "watermark",
        (),
        ("text/plain", "text/markdown", "text/html"),
        (
            "WritersLogic CPoE post-hoc semantic embedding watermark for paraphrase- and "
            "translation-robust manuscript identification"
        ),
        "2026-07-28T00:00:00.000Z",
        (),
        False,
    ),
    (
        48,
        "com.joinmonolith.sha256",
        "fingerprint",
        ("image", "video", "audio", "text", "application"),
        (),
        "Monolith SHA-256 content fingerprint for C2PA manifest recovery",
        "2026-07-29T00:00:00.000Z",
        ("https://api.joinmonolith.com/api/c2pa",),
        False,
    ),
    (
        49,
        "com.museblossom.contentsdefence.1",
        "watermark",
        ("image",),
        (),
        (
            "Contents Defence invisible image watermark, used to recover the associated C2PA "
            "manifest when embedded metadata is absent"
        ),
        "2026-08-10T00:00:00.000Z",
        (),
        False,
    ),
    (
        50,
        "me.reconize.videoseal.1",
        "watermark",
        ("image", "video"),
        (),
        (
            "Reconize deployment of the VideoSeal invisible watermark (Meta AI open research), "
            "embedding a 256-bit identity payload into image and video pixels via on-device Core ML"
        ),
        "2026-08-10T00:00:00.000Z",
        (),
        False,
    ),
    (
        51,
        "io.diker.sigi.v1",
        "watermark",
        ("image",),
        (),
        "Sigi invisible watermarking engine by Okeanos B.V",
        "2026-08-11T00:00:00.000Z",
        (),
        False,
    ),
    (
        52,
        "com.adobe.hiermark.A",
        "watermark",
        ("audio",),
        (),
        "Adobe Hierarchical Audio watermark (HierMark) variant A",
        "2026-08-13T12:00:00.000Z",
        (),
        False,
    ),
    (
        53,
        "com.adobe.flowmark.A",
        "watermark",
        ("video",),
        (),
        "Adobe FlowMark video watermarking variant A",
        "2026-08-13T12:00:00.000Z",
        (),
        False,
    ),
)
